name: Packer Golden Image Build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: packer-build
          audience: sts.amazonaws.com

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Build Golden Image
        id: packer-build
        working-directory: ./packer
        run: |
          packer init medusa.ubuntu.pkr.hcl
          packer validate medusa.ubuntu.pkr.hcl
          packer build -color=false -machine-readable medusa.ubuntu.pkr.hcl | tee build.log
          
          # Extract AMI ID and push to AWS SSM Parameter Store
          AMI_ID=$(grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2)
          echo "Generated AMI ID: $AMI_ID"
          
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT

      - name: Push the Golden AMI ID to Github repository variable
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          gh variable set GOLDEN_AMI_ID --repo ${{ github.repository }} --body "${{ steps.packer-build.outputs.ami_id }}"
